# Generated by Django 5.2.8 on 2026-08-10 19:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=200)),
                ('experience_required', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('work_model', models.CharField(blank=True, default='', max_length=50)),
                ('salary_range', models.CharField(blank=True, default='', max_length=120)),
                ('jd_text', models.TextField(blank=True, default='')),
                ('jd_quality', models.JSONField(blank=True, default=dict)),
                ('job_spec', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('form_id', models.CharField(blank=True, default='', max_length=120)),
                ('form_url', models.URLField(blank=True, default='')),
                ('sheet_id', models.CharField(blank=True, default='', max_length=120)),
                ('sheet_url', models.URLField(blank=True, default='')),
                ('question_ids', models.JSONField(blank=True, default=dict)),
                ('linkedin_post_id', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sync', 'Sync responses'), ('score', 'Re-score candidates')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total', models.IntegerField(default=0)),
                ('processed', models.IntegerField(default=0)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='hiring_app.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('github_username', models.CharField(blank=True, default='', max_length=120)),
                ('resume_drive_link', models.URLField(blank=True, default='')),
                ('resume_file_id', models.CharField(blank=True, default='', max_length=200)),
                ('resume_path', models.CharField(blank=True, default='', max_length=500)),
                ('resume_text', models.TextField(blank=True, default='')),
                ('profile', models.JSONField(blank=True, default=dict)),
                ('github_profile', models.JSONField(blank=True, default=dict)),
                ('score_detail', models.JSONField(blank=True, default=dict)),
                ('overall_score', models.FloatField(db_index=True, default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('recommendation', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('scored', 'Scored'), ('invited', 'Interview invited'), ('hired', 'Offer sent'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('interview_at', models.DateTimeField(blank=True, null=True)),
                ('recruiter_rating', models.IntegerField(blank=True, help_text="Recruiter's own 0-5 relevance rating, used to evaluate the scorer", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('recruiter_note', models.TextField(blank=True, default='')),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='hiring_app.campaign')),
            ],
            options={
                'ordering': ['-overall_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoogleOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_token', models.TextField(help_text='Fernet-encrypted Google OAuth2 credentials JSON')),
                ('scopes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google OAuth token',
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['owner', '-created_at'], name='hiring_app__owner_i_509661_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['owner', 'status'], name='hiring_app__owner_i_9b183a_idx'),
        ),
        migrations.AddIndex(
            model_name='backgroundjob',
            index=models.Index(fields=['campaign', '-created_at'], name='hiring_app__campaig_9f64ca_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['campaign', '-overall_score'], name='hiring_app__campaig_e35154_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['campaign', 'status'], name='hiring_app__campaig_61507a_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('campaign', 'response_id'), name='unique_response_per_campaign'),
        ),
    ]
