# Generated by Django 5.2.8 on 2026-08-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='interview_duration',
            field=models.IntegerField(blank=True, help_text='Minutes booked for the interview slot', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='interview_guide',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
